### ISSUE TITLE
Use Cargo insted of rustc

### ISSUE THREAD

**Issue by meltinglava** [Arxcis/adventofcode2018#15]
Cargo is rust package manager, that wraps the compiler. Since rust has the idea that the std only gives you the most common tools to make good libraries.
Also you now do not have to do a compile and then a run of the executable. `cargo run` does that all for you. It will also download, and compile all your dependencies. In my life i have only used rustc once. This is also necessary so that editors recognize all the code. Thinking of using [grabinput](https://crates.io/crates/grabinput) for grabbing all the input. as the code is redundant and the logic is not interesting.

Also you probably want to run `cargo run --release` to get the optimised version. Atleast one of the AOC is going to require some computation.

**Comment by meltinglava** [comment]
Also we need a naming scheme for naming folders to run tests in. rust does not live as one file.

**Comment by Arxcis** [comment]
If we can keep all programs to a single file without dependencies that would be preferable, just to keep the project as stupidly simple as possible. Maybe we will end up repeating some boring code, but I think it is worth it to avoid the complexity of language-specific folder-structure, dependency-managers, test-framework

My reasoning might not seem like a good one if you only consider `rust` in isolation, but consider if we end up with 10-15 different languages, and all of them have their own folder-structure, dependency-managers, test-framework. I think it is worth it not to go down that road. At least in the short-term. Perhaps it could be something to stretch for later if we run out of challanges :)

The line below executes your solution perfectly and passes the test
```
$ rustc main.rs -o main && cat input | ./main 
408
55250
```
Test
```
  ✔ day01-chronal-calibration › test › main.rs (903ms)

  1 test passed
```

If we want to compile equivelent of `cargo run --release` we can do the following
```
rustc main.rs -o main -C debuginfo=0 -C opt-level=3 && cat input | ./main 
```

We can still keep the `cargo` project if that is useful for an editor like you mentioned, but I would like to have a copy of the `main.rs` in the root of like this:
```
// Standalone single file solution, no dependencies
day01/main.rs

// Could also keep the cargo project here 
day01/rust/Cargo.lock
day01/rust/Cargo.toml
day01/rust/src/*
day01/rust/target/*
```

Does that sound like a good compromise, or super-stupid?
Any feedback/critique is welcome.

**Comment by meltinglava** [comment]
> My reasoning might not seem like a good one if you only consider `rust` in isolation.

That was my point. Most languages are fine living in one file. Rust rarly does.

Did day3 in rust. Ended up with 4 scorce files. As in rust you will need to make custom errortypes parsing the strings, to get code that you can easly work with. I know this is not what we like to see in this type of projects, but rusts safety module make the other code relly hard to reson about. Having that in main makes the files unbarable. 

editions: 
[rust 1.31](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html) now has a new editions. Editions are mostly managed by the Cargo.toml file. You can also use the `--editions` flag but you do not know what edition a file is. And then you only support one of the systems.


When testing the commands will be:

`cat day0*/target | cargo run --release --maifest-path day0*/rust_folder/Cargo.toml`
and then 
`cargo clean --maifest-path day0*/rust_folder/Cargo.toml`
cargo clean deletes the targets folder. 

There needs to be a naming convention for the rust folder here. could just be `rust`

**Comment by meltinglava** [comment]
Part 3 is in [my fork](https://github.com/meltinglava/adventofcode2018/tree/master/day03-no-matter-how-you-slice-it/rust)

**Comment by Arxcis** [comment]
Alright. I Appreciate your insight. Now I am curious to figure out more about the inner workings of Rust.
You have convinced me. I am ok with using cargo then, and we will see how it works out. I liked just `day*/rust` as naming convention.

I think we have to add a special case for rust when generating and running tests, but it is manageable.

**Comment by meltinglava** [comment]
Had a go trying to fix the tests, thow unsucsessful. My fork now has all day 01-03 in with the rust folders. Think you also need to pass the `--quiet` flag so that cargo does not print the compiling notes.

**Comment by Arxcis** [comment]
Cool. Maybe I should just pull from your fork then?

**Comment by meltinglava** [comment]
#45 is ready, thow tests will fail. Could not get ava to find the Cargo.toml files

**Comment by Arxcis** [comment]
Using cargo instead of rust now. Implementation tested and verified in 4046e59c9d1e09299487eabf54daeb95fa30499f.

Naming for rust folders has changed from `rust/` to `main.rs/`, to be more similar to the other names.
