### ISSUE TITLE
Troubles with passing input

### ISSUE THREAD

**Issue by tholok97** [Arxcis/adventofcode2018#16]
Day 3 requires the input to be read line-by-line. Doing `./main.bash $(cat input)` gives the input as a long array of strings for me, the newlines disappear. Doing `./main.bash "$(cat input)"` however does retain the newlines.

How do the other languages behave here? Is it Bash's fault, or does `$(cat input)` without quotes expand to a sequence of strings for you as well?

This is code I'm testing with:

```
CLAIMS="$@"

while read -r line; do
    echo "... $line ..."
done <<< "$CLAIMS"
```

`./main.bash $(cat input)` gives `... #1 @ 1,3: 4x4 #2 @ 3,1: 4x4 #3 @ 5,5: 2x2 ...`

`./main.bash "$(cat input)` gives 

```
... #1 @ 1,3: 4x4 ...
... #2 @ 3,1: 4x4 ...
... #3 @ 5,5: 2x2 ...
```

For now I'll solve using the quoted version. Passing input this way in AoC is new to me so I might be misunderstanding something here :yum:

**Comment by tholok97** [comment]
Source for example code: https://superuser.com/questions/284187/bash-iterating-over-lines-in-a-variable

**Comment by Arxcis** [comment]
Kanskje vi bare ska gå `cat input | ./main.bash` osv.  Rust løsningen gjør det allerede.

**Comment by Arxcis** [comment]
Fant ut at dette fungerte i `bash` for å lese fra pipe
```
while read var;
do
    RESULT=$(($RESULT + $var));
done;
```

**Comment by Arxcis** [comment]
Dette funka i go
```
lines := make([]string, 0)
s := bufio.NewScanner(os.Stdin)
for s.Scan() {
    lines = append(lines, s.Text())
}
```

**Comment by tholok97** [comment]
Okay så blir å endre fra å lese via kommandolineargument til å lese fra stdin?

**Comment by Arxcis** [comment]
Kan du fikse det i bash? Så tar eg de andre språkene?

**Comment by tholok97** [comment]
Yes can do :)

**Comment by Arxcis** [comment]
Nå du commiter så kan du gjøre `git commit -m "ref #16: ..melding"` for å line til dette issuet

**Comment by tholok97** [comment]
Hmmm får som jeg fortjener når jeg ikke bruker branches. Har jobba på master i forken min, så vet ikke helt hvordan jeg kan få laget en branch uten endringene jeg har laget. Har du en quickfix på det? git-fu

**Comment by tholok97** [comment]
Tror jeg løste det. Blir litt knoting med merging..

**Comment by Arxcis** [comment]
`git stash`

**Comment by Arxcis** [comment]
Ah herlig. Det gikk jo lekende lett. Inser jo at vi burde gjort det på denne måten fra starten av.
Er mye mer robust.

Problemet med args er jo når du får spaces, eller andre special characters som betyr noe i `bash` miljøet. 

Med stdin så er vi fri fra alt det maset der 👍

**Comment by Arxcis** [comment]
Has your input troubles gone away after switching to stdin?

**Comment by tholok97** [comment]
Pretty sure they have. Could always open again if it problem turns out not to be solved.

**Comment by Arxcis** [comment]
> Pretty sure they have. Could always open again if it problem turns out not to be solved.

tests are passing
```
$ npm run bash

  ✖ No tests found in day03-no-matter-how-you-slice-it/test.js
  ✔ day01-chronal-calibration › test › main.bash (3.3s)
  ✔ day02-inventory-management-system › test › main.bash (6.2s)

  2 tests passed

```
