### ISSUE TITLE
Only test the specific day and language you are making a pull request for

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/adventofcode2018#21]
Travis has an Environment variable `TRAVIS_PULL_REQUEST_BRANCH`

if people name their branches in a strict manner, we can use it to conditionally test only one language-day-pair:
* Branch `day01-js` -> `npm run js day01/`
* Branch `day01-rs` -> `npm run rs day01/`
* Branch `day02-py` -> `npm run py day02/`

else `npm run all`

**Comment by Arxcis** [comment]
Or maybe we should loook into using LABELS like explored in this post https://guyharwood.co.uk/2018/03/12/conditional-travis-builds-with-pull-request-labels/

**Comment by tholok97** [comment]
If someone made a change to another file by mistake this would not catch it though. Having Travis diff the PR branch to the master branch to find what files are changed would be a more magic solution that should be able to catch mistakes like that. Would also not require any special action on the PR makers part, which is nice.

Quick google indicates that this is achievable, but I don't have any concrete examples :smile:

**Comment by Arxcis** [comment]
Pull request #26 may solve this
