### ISSUE TITLE
Solutions to only day 1 or 2?

### ISSUE THREAD

**Issue by tholok97** [Arxcis/adventofcode2018#23]
Are solutions to only one part of a day "innafor" (:yum:), or do you think we should finish both before adding.

If there is a short and clear way to mark that a day has only been solved for part 1 or 2 in the table it could work out well :yum: 

Something like:

|   | day 3 | day 4
|--|--|--|
|Bash| *part 1 only*| X

Got my Bash day 3 part 1 down to 2 minutes (**from 2 hours**), so would love to add it.

**Comment by tholok97** [comment]
Hm tests fail because it expects answers for both part 1 & 2. IF partial answers are accepted there should be a way to specify testing for only one part.

**Comment by tholok97** [comment]
Both and part 1 and 2 are implemented now as #24, but the issue is still relevant for future solutions.

**Comment by Arxcis** [comment]
Pull request #26 may solve this
