### ISSUE TITLE
Refactor Bash solutions to follow Google style guide on naming

### ISSUE THREAD

**Issue by tholok97** [Arxcis/adventofcode2018#27]
The style guide: https://google.github.io/styleguide/shell.xml#Naming_Conventions.

I can do this myself of course, posting it here for reference later.

I've used uppercase for variables (except for loop variables for some reason) in the Bash solutions. I want to change it to follow the Google style guide that uses lower case for normal variables and upper case for constants (revolutionary idea! :o). Constants in Bash can be made with `readonly` and `declare -r` btw, never knew.

**Comment by tholok97** [comment]
I would add the "suggested improvement" label here, but I only @Arxcis has the power of labelling.

**Comment by Arxcis** [comment]
I would call the label just `improvement` since all improvement issues are implicitly suggestions. Then you have the standard tag `enhancement` === `improvement`

**Comment by tholok97** [comment]
Agreed :yum:

**Comment by Arxcis** [comment]
> The style guide: https://google.github.io/styleguide/shell.xml#Naming_Conventions.
> 
> I can do this myself of course, posting it here for reference later.
> 
> I've used uppercase for variables (except for loop variables for some reason) in the Bash solutions. I want to change it to follow the Google style guide that uses lower case for normal variables and upper case for constants (revolutionary idea! :o). Constants in Bash can be made with `readonly` and `declare -r` btw, never knew.

Cool initiative. Stretch goal for this issue would be to have some automated linting of the code standard, which travis could run and fail pull request if it does not follow guidelines.

**Comment by Arxcis** [comment]
Maybe failing is to harsh, but at least give some warning.

**Comment by tholok97** [comment]
https://github.com/koalaman/shellcheck <- is the static analysis tool we used this in operating systems.

Would be awesome to have Travis do this, but might stop people from submitting. Might be good to accept solutions that don't follow the style, and then instead fix it from inside the repo, to not scare potential contributors away?

**Comment by tholok97** [comment]
> But you cant even use an existing label?

This is what I see:

![image](https://user-images.githubusercontent.com/22896227/49508656-845ea700-f883-11e8-81c7-f0beceaadc81.png)

The only thing that is clickable is the label, and that just takes me to an overview of the issues under that label.

**Comment by tholok97** [comment]
Solved by #30.
